### ISSUE TITLE
[Request] Need new feature to offer trade (verified) or counter-offer

### ISSUE THREAD

**Issue by RudyMartin** [stashh-labs/stashh#17]
### Description

[Request] We need new feature to offer trade (verified) or counter-offer. This would boost activity and also really help collectors get their preferred NFTs. This trade feature would only be for items on $SCRT chains - collections already listed on the Stashh marketplace.

### Justification

Need a way to let a seller know I am interested but on different terms.

**Comment by scarylooking** [comment]
Offers are already in the pipeline - see https://stashh.io/roadmap for updates on progress
