### ISSUE TITLE
[Issue] Cannot open drafts

### ISSUE THREAD

**Issue by scarylooking** [stashh-labs/stashh#18]
### Reproduction Steps

1. Click Create
2. Select an existing or new collection
3. Click Single NFT
4. Enter the minimum required details
5. Click Save as Draft
6. Click View Collection Drafts
7. Click the magnifying glass icon on the Draft you just created

### Issue

Opening a draft results in a 404 page being shown

https://stashhapp-public-testnet.azurewebsites.net/asset/secret173zg5kc4677qcsc6lrr644385ec9tm5nh2s8dd/1647520155534_i2tkv

![image](https://user-images.githubusercontent.com/16178367/158808762-946d4ac0-ef88-49a0-8d9f-12ac7390810c.png)

### Expected Behavior

Draft should open for editing

### Reproducibility

Yes, every time

### Browser

Brave

**Comment by hieu-lai** [comment]
Unable to repro. Clicking on the magnifying glass will direct user to the asset page so they can view what it would look like. I assume this has now been fixed. The edit feature will be added soon.
