### ISSUE TITLE
[Issue] repeated prompts to authenticate when clicking the Buy Now button

### ISSUE THREAD

**Issue by scarylooking** [stashh-labs/stashh#24]
### Reproduction Steps

1. Clear local authentication data for a test wallet
2. Reload the site
3. Check the Menu to ensure you are not authenticated
4. Navigate to an NFT asset page
5. Click **Buy Now**
6. A message is shown saying you need to authenticate
7. Follow the instructions to Authenticate
8. A message is shown saying authentication was successful
9. Click **Buy Now**

### Issue

After authenticating a message is shown saying you need to authenticate.

### Expected behaviour

After authenticating the page should update its state so that the user is not repeatedly prompted to authenticate when they click the buy button

### Reproducibility

Yes, every time

### Environment

Testnet (testnet.stashh.io)

### Browser

Brave

**Comment by hieu-lai** [comment]
Unable to repro. I'm not getting the repeated prompts.
