### ISSUE TITLE
[Issue] suggested_price is called on every keypress

### ISSUE THREAD

**Issue by scarylooking** [stashh-labs/stashh#26]
### Reproduction Steps

1. Go through the Create NFT flow and select **Single NFT**
2. Open **Console** > **Network** and filter for `suggested_price`
3. Type into any field in the form, but don't toggle **Sell this NFT**
4. Nothing is shown in the console
5. Toggle **Sell this NFT** on
6. A number of requests are made to **suggested_price**
7. Type into, toggle or change any field of the form. 

### Issue

Every keystroke, state change, or toggle results in a new request to **suggested_price**

![image](https://user-images.githubusercontent.com/16178367/161430420-9b5a9ca6-138b-4a16-8b38-4633909b3fb9.png)

### Expected behaviour

**suggested_price** should only be called once

### Reproducibility

Yes, every time

### Environment

Mainnet (stashh.io)

### Browser

Brave

**Comment by hieu-lai** [comment]
Fixed
