### ISSUE TITLE
The collection of Secret Skulls have disappeared from Stashh.io marketplace. On my dashboard the 4 skulls I had purchased are gone :( What happened? Any chance I get back my skulls/ my sSCRT?[Issue]

### ISSUE THREAD

**Issue by AluBengalu** [stashh-labs/stashh#31]
### Reproduction Steps

12

### Issue

12

### Expected behaviour

12

### Error/Exception

```text
12
```

### Reproducibility

No, I could only make it happen once

### Environment

Mainnet (stashh.io)

### Browser

Chrome

### Notes

12

**Comment by scarylooking** [comment]
The person who created the collection copied the artwork from somewhere else. The owner of the original artwork contacted Stashh to complain so we had to take down the collection.
