### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by asap-aurel** [stashh-labs/stashh#32]
### Reproduction Steps

1. I try to get in the Testnet to do the last steps for my NFT collection but after authentificate and request funds the webside tell me thats my scrt adress is invalid... 
2. I am sure to be on Testnet, did all the steps before and my adress is ledgit.
3. please help me to use stashh marketplace 

### Issue

invalid secret wallet adress

### Expected behaviour

get some help to fix this problem

### Reproducibility

Yes, every time

### Environment

Testnet (testnet.stashh.io)

### Browser

Brave

**Comment by asap-aurel** [comment]
?

**Comment by scarylooking** [comment]
For general questions please use Discord https://discord.gg/DGVPXfWXgz
